version: '3.4'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    ports:
      - 8888:8888
    ipc: host
    privileged: true  
    runtime: nvidia
    environment:
      - DISPLAY=unix${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - $HOME/limo_data:/limo_data 
      - /tmp/.X11-unix:/tmp/.X11-unix
    # network_mode: host #  error: conflicting options: host type networking can't be used with links comment to avoid it
    stdin_open: true
    tty: true
