version: "3.8"

services:
  limo:
    # Use the same user as the host
    user: <uid>:<gid>
    volumes:
      - /home/<username>:/home/<username>
    # Withtout this the nvidia driver does not allow for creating opengl
    # contexts inside the container.
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # This passes the nvidia graphics card into the container.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]